# -*- coding: utf-8 -*-
"""Traffic_Shop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mIrR9zjT6yendXFP4BL4UShNgRAOlumH
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
# %matplotlib inline

df_table = pd.read_excel('./Traffic_Shop_new.xlsx',sheet_name='Data')

print(df_table)

df_table_season = pd.read_excel('./Traffic_Shop_new.xlsx',sheet_name='Season_Data')

print(df_table_season)

df_table.head()

df_table_season.head()

#On this graph we can see that the most traafic we got before and on holidays like Worldwide Woman Year(nearly 8th of March), Christmas and New Year (second part of December-dirst part of January)

Scatter = df_table.plot.scatter(x='Traffic',y='Data',figsize=(10,17))
plt.show()

#On this graph we can see that the most traafic we got before and on holidays like Worldwide Woman Year(nearly 8th of March), Christmas and New Year (second part of December-first part of January)

Scatter = df_table.plot.scatter(x='Data',y='Traffic',figsize=(17,7))
plt.show()

df_table.plot(x='Data', y='Traffic',figsize=(20,10))
plt.show()

#The amount of traffic and total transaction per date is almost the same, the total_transactions is a bit lower than traffic
df_table['Traffic'].plot(figsize=(15,8))
df_table['Trans_total_obl'].plot(secondary_y=False, style='g')

#The biggest part of out brand`s advertisment belong to OOH, we haven`t got any TB advertisment
df = pd.DataFrame({'Kind of ardverisement': [14686.55, 58688 , 0],
                   'radius': [2439.7, 6051.8, 6378.1]},
                  index=['Radio', 'OOH', 'TB'])
plot = df.plot.pie(y='Kind of ardverisement', figsize=(7, 7))

#On that graph we can see that we have the biggest amount of transaction in Dnepropetrovskaya, Kharkovskaya and Kyivskaya areas, and the less amount is in Ternopolskaya and Khmelnitskaya areas 
df = pd.DataFrame({'lab':['Volinskaya', 'Dnepropetrovskaya', 'Zhitomirskaya','Zakarpatskaya','Zaporozhkaya','Ivano_Frankovskaya','Kyivskaya','Kirovogradskaya','Lvovskaya','Nikolayevskaya','Odesskaya','Poltavskaya','Sumskaya','Ternopolskaya','Kharkovskaya','Khmelnitskaya','Cherkasskaya'], 'val':[746103, 6806951, 711448, 810403, 2196941, 969349, 4165720, 543379, 2069444, 600602, 1553906, 1992473, 867930, 343592, 5618539, 385207,557638]})
ax = df.plot.bar(x='lab', y='val', rot=0,figsize=(23,8))

df_table['Kyivskaya'].plot()
df_table['Kyivskaya_OOH'].plot(secondary_y=True, style='g')

df_table['Dnepropetrovskaya'].plot()
df_table['Dnepropetrovskaya_OOH'].plot(secondary_y=True, style='g')

df_table['Kharkovskaya'].plot()
df_table['Kharkovskaya_OOH'].plot(secondary_y=True, style='g')

df_table['Ternopolskaya'].plot()
df_table['Ternopolskaya_OOH'].plot(secondary_y=True, style='g')

df_table['Khmelnitskaya'].plot()
df_table['Khmelnitskaya_OOH'].plot(secondary_y=True, style='g')

#Our brand is on the first place in OOH TRP
df = pd.DataFrame({'OOH TRP Brand vs Competitors': [58688,1996, 3669, 3553],
                  'radius': [2439.7, 6051.8, 6378.1, 5685.1]} ,
                  index=['Brand', 'Competitor1', 'Competitor2', 'Competitor3'])
plot = df.plot.pie(y='OOH TRP Brand vs Competitors', figsize=(7, 7))

#Our brand is on the second place in Radio TRP, the first is Competitor 2
df = pd.DataFrame({'Radio TRP Brand vs Competitors': [14687, 5915, 29296, 12245],
                  'radius': [2439.7, 6051.8, 6378.1, 5685.1]} ,
                  index=['Brand', 'Competitor1', 'Competitor2', 'Competitor3'])
plot = df.plot.pie(y='Radio TRP Brand vs Competitors', figsize=(7, 7))

"""Seasons"""

ax = df_table_season.plot(x ='Data', y='Traffic', kind = 'area',figsize=(15,7), alpha=0.5)
df_table_season.plot(x ='Data', y='Trans_total_obl', kind = 'area', figsize=(15,7), secondary_y=False, ax = ax, colormap='hsv', alpha=0.5)

#On this graph we compare amount of OOH TRP and Radio TRP by seasons. We have more OOH till spring 2018, after that Radio TRP was dominated. But generally amount of advertisement very decreased.
OOH = [7824,10822,9907,11359,8929,3685,2887,2789,483]
Radio = [1970,3077,3097,5052,6092,6800,7345,10313,3705]
index = ['Winter2017', 'Spring2017', 'Summer2017','Autumn2017','Winter2018','Spring2018','Summer2018','Autumn2018','Winter2018_2']
df = pd.DataFrame({'OOH': OOH,'Radio': Radio}, index=index)
ax = df.plot.bar(rot=0,figsize=(20,6))

#The bigget amount of Traffic and OOH+Radio TRP is in Autumn2017
from matplotlib import cm
OOH_Radio = [9794,13899,13064,16411,15021,10485,13021,13102,4188]
Traffic = [23954.76,43596.61,44228.85,53177.2,45819.44,47381.88,47853.67,48528.02,21213.92]
index = ['Winter2017', 'Spring2017', 'Summer2017','Autumn2017','Winter2018','Spring2018','Summer2018','Autumn2018','Winter2018_2']
df = pd.DataFrame({'OOH_Radio': OOH_Radio,'Traffic': Traffic}, index=index)
ax = df.plot.bar(rot=0,figsize=(20,6), colormap='PiYG')

"""Dollar impact on Traffic"""

Dollar = {'Season': ['Winter2017','Spring_2017','Summer2017','Autumn2017','Winter2018','Spring2018','Summer2018','Autumn2019','Winter2018_2'],
        'Traffic': [266164,335358,340321,348597,352457,364476,368105,373292,424278],
        'Dollar': [27.14995, 26.75, 25.9, 26.5, 27.7, 26.2, 26.7, 28.08, 27.7]
       }
  
df_dollar = pd.DataFrame(Dollar,columns=['Season','Traffic','Dollar'])
print (df_dollar)

#Our traffic not depends on Dollar
ax = df_dollar.plot(x ='Season', y='Traffic', kind = 'line',figsize=(15,8))
df_dollar.plot(x ='Season', y='Dollar', kind = 'line', figsize=(15,8), secondary_y=True, ax = ax)

